name: 🐳📦 Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      

      - name: Short the sha to 7 characters only
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA::7})

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository_owner }}/tour-of-heroes-api:${{ steps.vars.outputs.tag }}
            provenance: mode=max            
            cache-from: type=gha
            cache-to: type=gha,mode=max

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
            subject-name: ghcr.io/${{ github.repository_owner }}/tour-of-heroes-api
            subject-digest: ${{ steps.buildx.outputs.digest }}            