name: Generate release with attestation 🚀

on:
  push:
    tags:
      - 'v*'  # Este flujo de trabajo se ejecutará para cualquier etiqueta que comience con 'v'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Get the code 📚
      uses: actions/checkout@v4

    - name: Generate a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Release automática para la etiqueta ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Subir activos a la release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path/to/your/asset
        asset_name: nombre_del_activo
        asset_content_type: tipo_de_contenido
